sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"

install:
  - pip install .
  - pip install flask

script:
  - python setup.py test

notifications:
  email: false
