sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.5-dev"

install:
  - pip install .
  - pip install flask

script:
  - python setup.py test

notifications:
  email: false
